# Generated by Django 2.1 on 2018-08-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartertesting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
