# Generated by Django 2.1 on 2018-08-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartertesting', '0002_snobjecttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snobjecttype',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
