# Generated by Django 2.1 on 2018-08-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartertesting', '0003_auto_20180808_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='snobjecttype',
            name='code_name',
            field=models.CharField(default='', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
