# Generated by Django 2.1 on 2018-08-08 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartertesting', '0004_snobjecttype_code_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('sys_id', models.CharField(max_length=32, unique=True)),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sn_objects', to='smartertesting.SNObjectType')),
            ],
        ),
    ]
