# Generated by Django 2.1 on 2018-08-09 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartertesting', '0006_sntests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SNTests',
            new_name='SNTest',
        ),
    ]
