# Generated by Django 2.1 on 2018-08-09 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartertesting', '0007_auto_20180809_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNTestObjectRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=400)),
                ('sn_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_tests', to='smartertesting.SNObject')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_objects', to='smartertesting.SNTest')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sntestobjectrelation',
            unique_together={('test', 'sn_object')},
        ),
    ]
