# Generated by Django 2.1 on 2018-08-09 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartertesting', '0011_auto_20180809_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectUploadRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='smartertesting.SNObject')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='smartertesting.Upload')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='objectuploadrelation',
            unique_together={('upload', 'sn_object')},
        ),
    ]
